CREATE TABLE IF NOT EXISTS registrations (
  no text PRIMARY KEY,
  date text NOT NULL,
  name text NOT NULL,
  gender text NOT NULL,
  dob text NOT NULL,
  age integer NOT NULL,
  mobile text NOT NULL,
  k_sar text,
  k_gam text,
  k_tal text,
  k_pin text,
  h_sar text,
  h_gam text,
  h_tal text,
  h_pin text,
  fee integer NOT NULL,
  ts bigint NOT NULL,
  photo text,
  aadhar text,
  aadhar_no text,
  role text NOT NULL DEFAULT 'operator',
  status text NOT NULL DEFAULT 'pending',
  approved_by text,
  qr_code text
);

CREATE INDEX IF NOT EXISTS idx_registrations_status ON registrations(status);
CREATE INDEX IF NOT EXISTS idx_registrations_role ON registrations(role);

CREATE TABLE IF NOT EXISTS departments (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL UNIQUE,
  code text NOT NULL UNIQUE,
  head_name text NOT NULL DEFAULT '',
  status text NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'inactive'))
);

CREATE TABLE IF NOT EXISTS faculties (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  employee_code text NOT NULL UNIQUE,
  name text NOT NULL,
  department_id bigint NOT NULL REFERENCES departments(id),
  designation text NOT NULL DEFAULT '',
  faculty_type text NOT NULL DEFAULT 'custom',
  monthly_salary numeric NOT NULL CHECK (monthly_salary >= 0),
  joining_date text NOT NULL DEFAULT '',
  relieving_date text NOT NULL DEFAULT '',
  email text NOT NULL DEFAULT '',
  mobile text NOT NULL DEFAULT '',
  weekdays text NOT NULL DEFAULT '[0, 1, 2, 3, 4]',
  status text NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'inactive'))
);

CREATE TABLE IF NOT EXISTS monthly_attendance (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  faculty_id bigint NOT NULL REFERENCES faculties(id),
  attendance_date text NOT NULL,
  is_working integer NOT NULL DEFAULT 0 CHECK (is_working IN (0, 1)),
  attendance_status text NOT NULL DEFAULT '' CHECK (attendance_status IN ('', 'present', 'absent', 'leave', 'special')),
  leave_type text NOT NULL DEFAULT '' CHECK (leave_type IN ('', 'paid', 'unpaid')),
  remarks text NOT NULL DEFAULT '',
  UNIQUE (faculty_id, attendance_date),
  CHECK (attendance_status <> 'special' OR is_working = 0)
);

CREATE TABLE IF NOT EXISTS salary_records (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  faculty_id bigint NOT NULL REFERENCES faculties(id),
  month integer NOT NULL CHECK (month BETWEEN 1 AND 12),
  year integer NOT NULL CHECK (year >= 2000),
  snapshot text NOT NULL,
  status text NOT NULL DEFAULT 'draft' CHECK (status IN ('draft', 'finalized')),
  UNIQUE (faculty_id, month, year)
);

CREATE TABLE IF NOT EXISTS audit_logs (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  action text NOT NULL,
  module text NOT NULL,
  record_id text NOT NULL,
  old_data text NOT NULL DEFAULT '',
  new_data text NOT NULL DEFAULT '',
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_faculties_department_status ON faculties(department_id, status);
CREATE INDEX IF NOT EXISTS idx_monthly_attendance_faculty_date ON monthly_attendance(faculty_id, attendance_date);
CREATE INDEX IF NOT EXISTS idx_salary_records_period ON salary_records(year, month);
CREATE INDEX IF NOT EXISTS idx_audit_logs_created_at ON audit_logs(created_at);

ALTER TABLE departments ENABLE ROW LEVEL SECURITY;
ALTER TABLE faculties ENABLE ROW LEVEL SECURITY;
ALTER TABLE monthly_attendance ENABLE ROW LEVEL SECURITY;
ALTER TABLE salary_records ENABLE ROW LEVEL SECURITY;
ALTER TABLE audit_logs ENABLE ROW LEVEL SECURITY;

GRANT ALL ON TABLE departments, faculties, monthly_attendance, salary_records, audit_logs TO service_role;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO service_role;
